pull_request_rules:
  - name: Ready to merge
    conditions:
      - label=ready-to-merge
      - check-success~=^Preflight
      - check-success~=^Buildx
      - check-success~=^Analylze
      - check-success~=GitGuardian
    actions:
      merge:
        method: rebase
        rebase_fallback: none
