# Configuration for Prettier
# https://prettier.io/
# =============================================================================

# Configuration file:
# https://prettier.io/docs/en/configuration.html

# Options:
# https://prettier.io/docs/en/options.html

bracketSameLine: true
bracketSpacing: false
formatOnSave: true
proseWrap: 'always'
requireConfig: false
semi: true
singleQuote: true
trailingComma: all

# By setting this, the rest of the options in this file should be picked up by
# `.editorconfig` automatically
editorconfig: true
