[tool.poetry]
name = "gbclient"
version = "0.0.0"
description = "GitBook CLI tool and Python client library"
authors = ["Naomi Rose <23469+mechanomi@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]
black = { version = "^21.7b0", allow-prereleases = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gbclient = "gbclient.cli:run"

[tool.black]
line-length = 79
