name: Build and publish
on:
  pull_request:
  push:
    branches:
      - main    

jobs:
  docker:

    name: Building image for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    env:
      IMAGE_NAME: doitintl/docops/containers/python

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}-${{ matrix.python-version }}
      - uses: docker/build-push-action@v2
        with:
          context: images/python/base 
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VARIANT=${{ matrix.python-version }}
          secrets: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}