name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [dev, dev-python]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.image }}
          github-token: ${{ github.token }}
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: build
        with:
          build-args: VARIANT=${{ matrix.image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
  status:
    needs: build
    name: Status alert
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ravsamhq/notify-slack-action@v1
        if: always() && github.event_name != 'pull_request'
        env:
          STATUS: '{workflow} <{run_url}|{status_message}>'
          COMMIT: for commit `<{commit_url}|{commit_sha}>`
          BRANCH: on branch `{branch}`
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          notification_title: ''
          message_format: ${{ env.STATUS }} ${{ env.COMMIT }} ${{ env.BRANCH }}
          footer: <{repo_url}|{repo}>
          notify_when: success,warning,failure
