name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [dev, dev-python]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.image }}
          github-token: ${{ github.token }}
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: build
        with:
          build-args: VARIANT=${{ matrix.image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
