name: Lint checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    name: Run all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@v1.0.1
      - uses: nosborn/github-action-markdown-cli@v2.0.0
        if: always()
        with:
          files: .
          config_file: .markdownlint.yaml
      - uses: kasperhesthaven/setup-editorconfig-checker@v1.2.0
        if: always()
      - run: editorconfig-checker
      - uses: creyD/prettier_action@v4.0
        if: always()
        with:
          prettier_options: --check .
      - uses: jpetrucciani/black-check@master
        if: always()
