name: Packaging
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Python tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/doitintl/docops/devcontainer:main
    steps:
      - uses: actions/checkout@v2
      - run: cd poetry && make test
        env:
          GITBOOK_API_TOKEN: ${{ secrets.GITBOOK_API_TOKEN }}
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
      # - uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: logs-python-${{ matrix.version }}
      #     path: tests/logs
