name: Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-checks:
    name: Lint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@v1.0.1
      - uses: nosborn/github-action-markdown-cli@v2.0.0
        if: always()
        with:
          files: .
          config_file: .markdownlint.yaml
      - uses: kasperhesthaven/setup-editorconfig-checker@v1.2.0
        if: always()
      - run: editorconfig-checker
      - uses: creyD/prettier_action@v4.0
        if: always()
        with:
          prettier_options: --check .
      - uses: jpetrucciani/black-check@master
        if: always()
  # analysis:
  #   name: Static analysis
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ghcr.io/doitintl/docops/containers/python-3.9:main
  #     options: --user root
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.py }}
  #     - run: make analysis
  tests:
    name: Tests on Python ${{ matrix.py }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/doitintl/docops/containers/python-${{ matrix.py }}:main
      options: --user root
    strategy:
      matrix:
        py: ['3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - run: make test
        env:
          GITBOOK_API_TOKEN: ${{ secrets.GITBOOK_API_TOKEN }}
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs-python-${{ matrix.py }}
          path: tests/logs
