name: VS Code
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-changes:
    name: Test devcontainer changes
    runs-on: ubuntu-latest
    outputs:
      devcontainer: ${{ steps.filter.outputs.devcontainer }}
    steps:
      - uses: actions/checkout@v2
      # cspell:disable-next-line
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: ''
          filters: |
            devcontainer:
              - '.devcontainer/**'
  build:
    name: Build devcontainer
    needs: test-changes
    if: ${{ needs.test-changes.outputs.devcontainer == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # cspell:disable-next-line
      # - uses: hadolint/hadolint-action@v1.5.0
      #   with:
      #     dockerfile: ${{ env.SRC }}/Dockerfile
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/devcontainer
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
